#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
export TERM=xterm-256color
cat <<EOF
********************************************************************************

Welcome to Analythium's 1-Click ShinyProxy Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
Only these ports are open: 22 (SSH), 80 (HTTP), 443 (HTTPS).

   * Help and more information https://hub.analythium.io/
   * ShinyProxy documentation  https://www.shinyproxy.io/

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
